version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: flightmgmt_rabbitmq
    ports:
      - 8080:15672/tcp

  consumer:
    build: ./consumer
    container_name: flightmgmt_consumer
    restart: unless-stopped
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest

  publisher:
    build: ./publisher
    ports:
      - 80:80/tcp
    container_name: flightmgmt_publisher
    restart: unless-stopped
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
