version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: flightmgmt_rabbitmq

  consumer-app:
    depends_on:
      - rabbitmq
    build: ./consumer
    container_name: flightmgmt_consumer
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_PORT=15672

  publisher-app:
    depends_on:
      - rabbitmq
    build: ./publisher
    container_name: flightmgmt_publisher
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_PORT=15672
