apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\davey\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -c
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer
  namespace: kawa-foundation-app-dev
  name: consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\davey\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -c
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/flightmanagement-default: "true"
        io.kompose.service: consumer
    spec:
      containers:
        - env:
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_PASSWORD
              value: guest
            - name: RABBIT_USER
              value: guest
          image: consumer
          name: flightmgmt-consumer
          ports:
            - containerPort: 5000
              hostPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
