apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/flightmanagement-default: "true"
        io.kompose.service: consumer
    spec:
      containers:
        - env:
            - name: RABBIT_HOST
              value: rabbitmq
            - name: RABBIT_PASSWORD
              value: guest
            - name: RABBIT_USER
              value: guest
          image: consumer
          name: flightmgmt-consumer
          resources: {}
      restartPolicy: Always
status: {}
