apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\davey\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -c
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: publisher-app
  name: publisher-app
  namespace: default
spec:
  ports:
    - name: "https"
      port: 443
      targetPort: 5000
  selector:
    io.kompose.service: publisher-app
status:
  loadBalancer: {}
