apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\davey\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -c
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\davey\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -c
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/flightmanagement-default: "true"
        io.kompose.service: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3.11-management
          name: flightmgmt-rabbitmq
          resources: {}
      restartPolicy: Always
status: {}
