apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\davey\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert -c
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
  namespace: default
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 15672
  selector:
    io.kompose.service: rabbitmq
status:
  loadBalancer: {}
